databases:
  - name: insta-feed-postgres
    ipAllowList: [] # only allow internal connections

services:
  - type: web
    name: sild-insta-pull
    env: node
    repo: https://github.com/tush241191/vidtreon-insta-api.git
    buildCommand: "yarn"
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: insta-feed-postgres
          property: connectionString
