databases:
  - name: insta-feed-postgres
    ipAllowList: [] # only allow internal connections

services:
  - type: web
    name: sild-insta-pull
    env: node
    repo: https://github.com/tush241191/vidtreon-insta-api.git
    buildCommand: "./bin/build.sh"
    startCommand: "node server.js"
    envVars:
      - key: JWT_TOKEN_KEY
        value: ulH^ttqk%F5nU8T5iKk@2Ckb^BT*sK$He@JBMfbDGa8&ZlC9*8P1ji&u@xX1
      - key: DATABASE_URL
        fromDatabase:
          name: insta-feed-postgres
          property: connectionString
