export const PURCHASE_STATE_PENDING = 'pending';
export const PURCHASE_STATE_INVOICE = 'invoice';
export const PURCHASE_STATE_PAID = 'paid';
export const PURCHASE_STATE_FAILED = 'failed';

export const PURCHASE_STATES = [
  PURCHASE_STATE_PENDING,
  PURCHASE_STATE_INVOICE,
  PURCHASE_STATE_PAID,
  PURCHASE_STATE_FAILED
]
